extern int WIDTH;
extern int HEIGHT;
extern int DPI;
extern int RESX;
extern int RESY;
extern int TARGET_FPS;
extern double MOUSEX;
extern double MOUSEY;
extern const int CORNER;
extern const int CENTER;
extern int RECTMODE;
extern int IMAGEMODE;
extern glm::vec3 FILLCOLOR;
extern bool NOLOOP;
extern const short PREFERRED_WIDTH;
extern const short PREFERRED_HEIGHT;
extern bool LOOPING;
extern glm::vec2 TRANSLATE;
extern float ROTATE;
extern std::vector<glm::vec2> * TRANSLATE_STACK;
extern std::vector<float> * ROTATE_STACK;
extern const float PI;
extern const float TWO_PI;
extern const int RADIANS;
extern const int DEGREES;
extern int ANGLEMODE;
extern int LINEWEIGHT;
extern std::vector<int> * RECTMODE_STACK;
